### ISSUE TITLE
may you share links to understand theory for An implementation of Hellinger-Distance Based Concept Drift Detection

### ISSUE THREAD

**Issue by Sandy4321** [ThomasBoot/Concept_Drift_HDDDM#1]
may you share links to understand theory for An implementation of Hellinger-Distance Based Concept Drift Detection

**Comment by ThomasBoot** [comment]
Background theory regarding Hellinger Distance based drift detection is provided in:

G. Ditzler and R. Polikar, "Hellinger distance based drift detection for nonstationary environments," 2011 IEEE Symposium on Computational Intelligence in Dynamic and Uncertain Environments (CIDUE), 2011, pp. 41-48, doi: 10.1109/CIDUE.2011.5948491.

Other theory used is referenced accordingly in our paper on github.

**Comment by Sandy4321** [comment]
thanks by the way what is gut hub link for reference 8 from your paper 
[8] Idriss. Github: drift hdddm.

**Comment by ThomasBoot** [comment]
https://github.com/IdrissMg/DriftDetection/blob/master/drift_HDDDM.py

**Comment by Sandy4321** [comment]
how different it is from https://github.com/mitre/menelaus

https://paperswithcode.com/paper/hellinger-distance-based-drift-detection-for#code
